version: '3.1'

volumes:
  data:
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data
  backend:
    container_name: backend
    image: node:lts-alpine
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '3000:3000'
      - '5555:5555'
    networks:
      - network
    volumes:
      - ./srcs/backend:/backend
    working_dir: /backend
    command: >
      sh -c "npm install &&
      npx prisma migrate dev &&
      npm run start:dev"
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    image: node:lts-alpine
    environment:
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
    ports:
      - '4200:4200'
    networks:
    - network
    volumes:
      - ./srcs/frontend:/frontend
    working_dir: /frontend
    command: >
      sh -c "apk add openssl &&
      openssl req -new -newkey rsa:4096 -nodes -subj "/C=/ST=/L=/O=/CN=" -keyout server.key -out server.csr &&
      openssl x509 -req -sha256 -days 365 -in server.csr -signkey server.key -out server.pem &&
      npm install &&
      npm install -g @angular/cli &&
      ng serve -o --ssl true --ssl-key server.key --ssl-cert server.pem --host 0.0.0.0 --disable-host-check"
    depends_on:
      - backend

networks:
  network:
