name: Node.js CI

on:
  push:
    branches: [ "pong_test" ]
  pull_request:
    branches: [ "pong_test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: test front
      run: |
        cd srcs/frontend
        npm ci
        npm run build --if-present
        npm test
    - name: test back
      run: |
        cd srcs/backend
        npm ci
        npm run build --if-present
        npm test

